name: Format Check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK 1.7
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10'
        distribution: 'adopt'
    - name: Run scalafmtAll format
      run: sbt scalafmtAll
    - name: Run scalafix check
      run: sbt "scalafixAll --check"
